### ISSUE TITLE
ffmpeg example complication failed

### ISSUE THREAD

**Issue by othmoz** [nuxeo/docker-nuxeo#19]
Hi, when I fire up docker-composer up to build and run my image, I get an error:

```
/tmp/ffmpeg-nuxeo
Cloning into 'x264'...
/tmp/ffmpeg-nuxeo/x264 /tmp/ffmpeg-nuxeo
Switched to a new branch 'stable'
Branch stable set up to track remote branch stable from origin.
Found no assembler
Minimum version is nasm-2.13
If you really want to compile without asm, configure with --disable-asm.
ERROR: Service 'web' failed to build: The command '/bin/sh -c ./prepare-packages.sh  && ./build-yasm.sh  && ./build-x264.sh  && ./build-libvpx.sh  && ./build-ffmpeg.sh  && cd /tmp  && rm -Rf ffmpeg-nuxeo  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

Here is my Dockerfile as instructed by https://hub.docker.com/_/nuxeo/:
```
FROM nuxeo:latest

ADD nuxeo.conf /docker-entrypoint-initnuxeo.d/nuxeo.conf

# install ffmpeg
USER root

RUN echo "deb http://httpredir.debian.org/debian jessie non-free" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y --no-install-recommends libfaac-dev git

WORKDIR /tmp
# Build ffmpeg
ENV BUILD_YASM true
ENV LIBFAAC true
RUN git clone https://github.com/nuxeo/ffmpeg-nuxeo.git
WORKDIR ffmpeg-nuxeo
RUN ./prepare-packages.sh \
 && ./build-yasm.sh \
 && ./build-x264.sh \
 && ./build-libvpx.sh \
 && ./build-ffmpeg.sh \
 && cd /tmp \
 && rm -Rf ffmpeg-nuxeo \
 && rm -rf /var/lib/apt/lists/*

USER 1000
```

and here is my docker-composer.yml:
```
version: '3'
services:
 web:
  build: ./mynuxeo
   #image: username/repo:tag
  ports:
   - "8080:8080"
  environment:
   - NUXEO_PACKAGES=nuxeo-jsf-ui nuxeo-drive nuxeo-dam nuxeo-spreadsheet nuxeo-easyshare
   - NUXEO_TEMPLATES=postgres
   - NUXEO_DB_TYPE=postgres
   - NUXEO_DB_HOST=db
   - NUXEO_DB_NAME=nuxeo
   - NUXEO_DB_USER=nuxeo
   - NUXEO_DB_PASSWORD=nuxeoDBPW
  volumes:
   - nuxeo-data:/var/lib/nuxeo/data
  depends_on:
   - db
 db:
  image: nuxeo/postgres
  environment:
   - POSTGRES_USER=nuxeo
   - POSTGRES_PASSWORD=nuxeoDBPW
   - POSTGRES_DB=nuxeo
  volumes:
   - db-data:/var/lib/postgresql/data
volumes:
 nuxeo-data:
 db-data:
```
Any help is appreciated
